// <auto-generated/> - Codegen configuration constants
namespace Bsharp.Codegen;

/// <summary>
/// Configuration constants for bsharp code generation.
/// </summary>
internal static class CodegenConstants {
    /// <summary>
    /// Maximum number of diagnostic entries to include in audit output for each category.
    /// Prevents overwhelming output for projects with many occurrences.
    /// </summary>
    public const int MaxDiagnosticEntries = 200;

    /// <summary>
    /// Default target framework for generated host projects when none is specified.
    /// </summary>
    public const string DefaultTargetFramework = "net11.0";

    /// <summary>
    /// Default runtime version fallback when runtime version cannot be determined.
    /// </summary>
    public const string DefaultRuntimeVersion = "11.0.0";

    /// <summary>
    /// System.IO.Hashing package version pinned to match the SDK shipping version.
    /// Used for Tasks.Hash utility in generated code.
    /// </summary>
    public const string SystemIOHashingVersion = "11.0.0-preview.4.26208.110";
}
