// <auto-generated/> - Go host emitter (foundation scaffolding)
#nullable enable
using Microsoft.Build.Construction;
using Microsoft.Build.Execution;
using System.Text;
using System.Text.Json;

namespace Bsharp.Codegen;

/// <summary>
/// Foundation-only Go host emitter. This is intentionally a thin shell:
/// it loads the project, walks the ProjectInstance, and emits a Go module
/// with stub target bodies plus a self-describing emit-report.json. It is
/// NOT a working build host yet; target bodies panic with
/// runtime.NotImplemented when invoked.
///
/// The point of this scaffold is to make every subsequent emission task
/// fail loudly at codegen time (or at runtime panic) so we can grow real
/// emission piece-by-piece without ever producing silently-wrong Go.
/// </summary>
internal static class GoEmitter {
    public static int Emit(
        ProjectInstance instance,
        string outDir,
        IReadOnlyList<string>? requestedTargets,
        Dictionary<string, string> globalProps,
        string runtimeReplacePath
    ) {
        Directory.CreateDirectory(outDir);
        var report = new EmitReport();

        var mainGo = BuildMainGo(instance, requestedTargets, report);
        var goMod = BuildGoMod(runtimeReplacePath);

        File.WriteAllText(Path.Combine(outDir, "main.go"), mainGo);
        File.WriteAllText(Path.Combine(outDir, "go.mod"), goMod);
        File.WriteAllText(Path.Combine(outDir, "emit-report.json"),
            JsonSerializer.Serialize(report, new JsonSerializerOptions { WriteIndented = true }));

        Console.Error.WriteLine($"codegen: --emit-go wrote main.go ({mainGo.Length} chars), go.mod, emit-report.json to {outDir}");
        Console.Error.WriteLine($"codegen: --emit-go status: {report.Targets.Total} targets ({report.Targets.RealBody} real-body, {report.Targets.StubBody} stub)");
        Console.Error.WriteLine($"codegen: --emit-go Phase A: complex targets still panic; see emit-report.json for per-reason counts.");
        return 0;
    }

    static string BuildMainGo(ProjectInstance instance, IReadOnlyList<string>? requestedTargets, EmitReport report) {
        var sb = new StringBuilder();
        sb.AppendLine("// Code generated by bsharp codegen --emit-go. DO NOT EDIT.");
        sb.AppendLine("//");
        sb.AppendLine("// Foundation scaffold only. Target bodies are NOT implemented; calling");
        sb.AppendLine("// any target will panic via runtime.NotImplemented. Use this file as a");
        sb.AppendLine("// shape reference for the real emitter that will land in follow-up work.");
        sb.AppendLine("package main");
        sb.AppendLine();
        sb.AppendLine("import (");
        sb.AppendLine("\t\"fmt\"");
        sb.AppendLine("\t\"os\"");
        sb.AppendLine("\t\"strings\"");
        sb.AppendLine();
        sb.AppendLine("\trt \"github.com/simonrozsival/bsharp-host-go/runtime\"");
        sb.AppendLine(")");
        sb.AppendLine();

        EmitProperties(sb, instance, report);
        EmitItems(sb, instance, report);
        EmitTargetStubs(sb, instance, report);
        EmitMain(sb, instance, requestedTargets);

        return sb.ToString();
    }

    static void EmitProperties(StringBuilder sb, ProjectInstance instance, EmitReport report) {
        var properties = instance.Properties
            .Where(p => !string.IsNullOrEmpty(p.Name))
            .OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        report.Properties.Total = properties.Length;
        report.Properties.SupportedLiteral = 0;

        sb.AppendLine("// P captures the initial property snapshot. Real codegen will route");
        sb.AppendLine("// dynamic mutations through typed setters; for now it's a value-bag.");
        sb.AppendLine("type properties struct {");
        sb.AppendLine("\textras map[string]string");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("func (p *properties) Get(name string) string {");
        sb.AppendLine("\tif p.extras == nil { return \"\" }");
        sb.AppendLine("\treturn p.extras[strings.ToLower(name)]");
        sb.AppendLine("}");
        sb.AppendLine("func (p *properties) Set(name, value string) {");
        sb.AppendLine("\tif p.extras == nil { p.extras = make(map[string]string) }");
        sb.AppendLine("\tp.extras[strings.ToLower(name)] = value");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("var P = &properties{ extras: map[string]string{");
        foreach (var prop in properties) {
            sb.Append("\t\"").Append(prop.Name.ToLowerInvariant()).Append("\": ");
            sb.Append(GoStringLiteral(prop.EvaluatedValue));
            sb.AppendLine(",");
            report.Properties.SupportedLiteral++;
        }
        sb.AppendLine("}}");
        sb.AppendLine();
    }

    static void EmitItems(StringBuilder sb, ProjectInstance instance, EmitReport report) {
        var byType = instance.Items
            .GroupBy(i => i.ItemType, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        report.Items.TotalTypes = byType.Length;
        report.Items.TotalItems = instance.Items.Count;
        report.Items.SupportedLiteral = 0;

        sb.AppendLine("// I holds typed item lists, keyed by lowercased item type. Generated.");
        sb.AppendLine("type items struct {");
        sb.AppendLine("\tlists map[string][]*rt.Item");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("func (it *items) Get(name string) []*rt.Item {");
        sb.AppendLine("\treturn it.lists[strings.ToLower(name)]");
        sb.AppendLine("}");
        sb.AppendLine("func (it *items) AppendTo(name string, more []*rt.Item) {");
        sb.AppendLine("\tk := strings.ToLower(name)");
        sb.AppendLine("\tit.lists[k] = append(it.lists[k], more...)");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("var I = newItems()");
        sb.AppendLine();
        sb.AppendLine("func newItems() *items {");
        sb.AppendLine("\tit := &items{ lists: map[string][]*rt.Item{} }");
        foreach (var group in byType) {
            sb.Append("\tit.lists[\"").Append(group.Key.ToLowerInvariant()).Append("\"] = []*rt.Item{");
            var any = false;
            foreach (var item in group) {
                if (any) sb.Append(", ");
                sb.Append("rt.NewItem(").Append(GoStringLiteral(item.EvaluatedInclude)).Append(")");
                any = true;
                report.Items.SupportedLiteral++;
            }
            sb.AppendLine("}");
        }
        sb.AppendLine("\treturn it");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitTargetStubs(StringBuilder sb, ProjectInstance instance, EmitReport report) {
        var targets = instance.Targets.Values
            .OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        report.Targets.Total = targets.Length;
        report.Targets.RealBody = 0;
        report.Targets.StubBody = 0;
        report.Targets.UnsupportedReasons = new SortedDictionary<string, int>(StringComparer.Ordinal);

        var targetIndex = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var nameSet = new HashSet<string>(StringComparer.Ordinal);
        foreach (var target in targets) {
            targetIndex[target.Name] = SanitizeTargetName(target.Name, nameSet);
        }

        sb.AppendLine("// Generated target functions. Each target is classified as one of:");
        sb.AppendLine("//   - real-body: emitted from MSBuild XML using runtime.Expand / runtime.EvalCondition");
        sb.AppendLine("//   - stub:      panics via runtime.NotImplemented (Phase A doesn't yet handle the construct)");
        sb.AppendLine("// See emit-report.json for the classification per target.");
        sb.AppendLine();

        foreach (var target in targets) {
            var ident = targetIndex[target.Name];
            var reason = ClassifyTarget(target);
            if (reason == null) {
                EmitRealTargetBody(sb, target, ident, targetIndex);
                report.Targets.RealBody++;
            } else {
                EmitStubTargetBody(sb, target, ident, reason);
                report.Targets.StubBody++;
                report.Targets.UnsupportedReasons.TryGetValue(reason, out var c);
                report.Targets.UnsupportedReasons[reason] = c + 1;
            }
        }

        sb.AppendLine("// dispatchTarget maps target names to functions. Generated.");
        sb.AppendLine("func dispatchTarget(name string) bool {");
        sb.AppendLine("\tswitch strings.ToLower(name) {");
        foreach (var target in targets) {
            sb.Append("\tcase ").Append(GoStringLiteral(target.Name.ToLowerInvariant())).Append(":");
            sb.AppendLine();
            sb.Append("\t\t").Append(targetIndex[target.Name]).AppendLine("()");
            sb.AppendLine("\t\treturn true");
        }
        sb.AppendLine("\t}");
        sb.AppendLine("\treturn false");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitStubTargetBody(StringBuilder sb, ProjectTargetInstance target, string ident, string reason) {
        sb.Append("// ").Append(target.Name).Append(": stub — ").AppendLine(reason);
        sb.Append("func ").Append(ident).AppendLine("() {");
        sb.Append("\trt.NotImplemented(").Append(GoStringLiteral(target.Name)).AppendLine(")");
        sb.AppendLine("\tpanic(\"target body not yet emitted: " + EscapeForGo(target.Name) + " — " + EscapeForGo(reason) + "\")");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitRealTargetBody(StringBuilder sb, ProjectTargetInstance target, string ident, Dictionary<string, string> targetIndex) {
        sb.Append("// ").Append(target.Name).AppendLine(": real body");
        sb.Append("func ").Append(ident).AppendLine("() {");
        sb.Append("\tts := rt.GetTargetState(").Append(GoStringLiteral(target.Name)).AppendLine(")");
        sb.AppendLine("\tif !ts.TryEnter() { return }");

        if (!string.IsNullOrWhiteSpace(target.DependsOnTargets)) {
            foreach (var dep in target.DependsOnTargets.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)) {
                if (targetIndex.TryGetValue(dep, out var depIdent)) {
                    sb.Append("\t").Append(depIdent).AppendLine("()")
                      .Append("");
                }
            }
        }

        if (!string.IsNullOrWhiteSpace(target.Condition)) {
            sb.Append("\tif !rt.MustEvalCondition(").Append(GoStringLiteral(target.Condition)).AppendLine(", P, I) { ts.MarkSkipped(); return }");
        }

        sb.Append("\tstarted := rt.Log.TargetStarted(").Append(GoStringLiteral(target.Name)).AppendLine(")");

        foreach (var child in target.Children) {
            if (child is ProjectTaskInstance task) {
                EmitLocalTaskCall(sb, target, task);
            }
        }

        sb.Append("\trt.Log.TargetFinished(").Append(GoStringLiteral(target.Name)).AppendLine(", started)");
        sb.AppendLine("\tts.MarkDone()");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitLocalTaskCall(StringBuilder sb, ProjectTargetInstance target, ProjectTaskInstance task) {
        var fn = LocalTaskGoFunc(task.Name);
        if (fn == null) {
            sb.Append("\trt.NotImplemented(").Append(GoStringLiteral(target.Name + ":" + task.Name)).AppendLine(")");
            return;
        }

        if (!string.IsNullOrWhiteSpace(task.Condition)) {
            sb.Append("\tif rt.MustEvalCondition(").Append(GoStringLiteral(task.Condition)).AppendLine(", P, I) {");
        }

        sb.Append("\tif err := rt.").Append(fn).Append("(rt.NewParamList(");
        var first = true;
        foreach (var param in task.Parameters) {
            if (!first) sb.Append(", ");
            first = false;
            sb.Append("rt.Param{Key: ").Append(GoStringLiteral(param.Key))
              .Append(", Value: rt.MustExpand(").Append(GoStringLiteral(param.Value)).Append(", P, I, nil)}");
        }
        sb.Append("));");

        // Tasks that take ItemBag/OutputList come in two flavors. Our Phase A
        // classifier rejected any task with an <Output/>, so we know there are
        // no outputs to wire — pass nil/empty for ItemBag.
        if (TaskNeedsItemBag(task.Name)) {
            // Replace closing paren with the extra args. The last char written
            // was ");" — strip the trailing ");" and re-emit with outputs nil.
            sb.Length -= 2;
            sb.Append(", nil, I);");
        }
        sb.AppendLine(" err != nil { rt.GetErrorList().Add(\"" + EscapeForGo(target.Name) + "\", err) }");

        if (!string.IsNullOrWhiteSpace(task.Condition)) {
            sb.AppendLine("\t}");
        }
    }

    // ClassifyTarget returns null if the target can be emitted with a real
    // body, or a short reason string otherwise.
    static string? ClassifyTarget(ProjectTargetInstance target) {
        if (ContainsBatching(target.Inputs) || ContainsBatching(target.Outputs)) {
            return "target-batching";
        }
        if (!string.IsNullOrWhiteSpace(target.Inputs) || !string.IsNullOrWhiteSpace(target.Outputs)) {
            return "target-inputs-outputs";
        }
        if (target.BeforeTargets is { Length: > 0 } || target.AfterTargets is { Length: > 0 }) {
            // Before/After hooks need a different dispatch model; defer.
            return "before-after-targets";
        }
        if (!string.IsNullOrWhiteSpace(target.DependsOnTargets) && target.DependsOnTargets.IndexOfAny(new[] { '$', '@', '%' }) >= 0) {
            return "dynamic-depends-on-targets";
        }
        if (!IsSimpleConditionTemplate(target.Condition)) {
            return "complex-target-condition";
        }
        foreach (var child in target.Children) {
            switch (child) {
                case ProjectTaskInstance task:
                    if (LocalTaskGoFunc(task.Name) == null) return "task:" + task.Name;
                    if (task.Outputs.Count > 0) return "task-has-outputs:" + task.Name;
                    if (!IsSimpleConditionTemplate(task.Condition)) return "complex-task-condition";
                    foreach (var p in task.Parameters) {
                        if (!IsSimpleExpressionTemplate(p.Value)) return "complex-task-param:" + task.Name + "." + p.Key;
                        if (ContainsBatching(p.Value)) return "task-batching";
                    }
                    break;
                case ProjectPropertyGroupTaskInstance:
                    return "property-group-in-target";
                case ProjectItemGroupTaskInstance:
                    return "item-group-in-target";
                case ProjectOnErrorInstance:
                    return "on-error";
                default:
                    return "unknown-target-child";
            }
        }
        return null;
    }

    // LocalTaskGoFunc maps an MSBuild task name to the Go runtime helper name.
    // Returns null for tasks we don't have a local implementation for yet.
    static string? LocalTaskGoFunc(string taskName) => taskName switch {
        "Message" => "Message",
        "Warning" => "Warning",
        "Error"   => "Error",
        "MakeDir" => "MakeDir",
        "RemoveDir" => "RemoveDir",
        "Touch"   => "Touch",
        "Delete"  => "Delete",
        "Copy"    => "Copy",
        "WriteLinesToFile" => "WriteLinesToFile",
        "ReadLinesFromFile" => "ReadLinesFromFile",
        _ => null,
    };

    static bool TaskNeedsItemBag(string taskName) => taskName switch {
        "MakeDir" or "RemoveDir" or "Touch" or "Delete" or "Copy" or "ReadLinesFromFile" => true,
        _ => false,
    };

    // IsSimpleExpressionTemplate returns true if `template` only uses constructs
    // the Phase A runtime.Expand evaluator handles: literals, $(X), @(Y) (no
    // transforms), %(Z). Returns false on anything more complex.
    static bool IsSimpleExpressionTemplate(string? template) {
        if (string.IsNullOrEmpty(template)) return true;
        for (int i = 0; i < template.Length; i++) {
            var c = template[i];
            if (c == '$' || c == '@' || c == '%') {
                if (i + 1 >= template.Length || template[i + 1] != '(') continue;
                var end = FindMatchingParen(template, i + 1);
                if (end < 0) return false;
                var inner = template.Substring(i + 2, end - i - 2);
                if (c == '$' && inner.IndexOfAny(new[] { '.', '(', '[', ':' }) >= 0) return false;
                if (c == '@' && inner.Contains("->")) return false;
                i = end;
            }
        }
        return true;
    }

    static bool IsSimpleConditionTemplate(string? condition) {
        if (string.IsNullOrWhiteSpace(condition)) return true;
        // Reject any of the well-known Phase B+ markers.
        if (condition.IndexOf("Exists", StringComparison.OrdinalIgnoreCase) >= 0) return false;
        if (condition.IndexOf("HasTrailingSlash", StringComparison.OrdinalIgnoreCase) >= 0) return false;
        if (condition.IndexOf("MSBuild::", StringComparison.Ordinal) >= 0) return false;
        if (condition.IndexOf("System.", StringComparison.Ordinal) >= 0) return false;
        if (condition.IndexOf("::", StringComparison.Ordinal) >= 0) return false;
        // Allow only $(Prop) / @(Items) / %(Meta) and quoted strings; reject
        // property functions like $(X.ToLower()).
        for (int i = 0; i < condition.Length; i++) {
            if (condition[i] == '$' && i + 1 < condition.Length && condition[i + 1] == '(') {
                var end = FindMatchingParen(condition, i + 1);
                if (end < 0) return false;
                var inner = condition.Substring(i + 2, end - i - 2);
                if (inner.IndexOfAny(new[] { '.', '(' }) >= 0) return false;
                i = end;
            }
        }
        return true;
    }

    static int FindMatchingParen(string s, int openIdx) {
        var depth = 0;
        for (int i = openIdx; i < s.Length; i++) {
            if (s[i] == '(') depth++;
            else if (s[i] == ')') { depth--; if (depth == 0) return i; }
        }
        return -1;
    }

    static bool ContainsBatching(string? value) {
        if (string.IsNullOrEmpty(value)) return false;
        for (int i = 0; i + 1 < value.Length; i++) {
            if (value[i] == '%' && value[i + 1] == '(') return true;
        }
        return false;
    }

    static void EmitMain(StringBuilder sb, ProjectInstance instance, IReadOnlyList<string>? requestedTargets) {
        var defaultEntry = requestedTargets is { Count: > 0 } ? requestedTargets[0] : (instance.DefaultTargets.FirstOrDefault() ?? "Build");
        sb.AppendLine("func main() {");
        sb.AppendLine("\trt.Log.Level = rt.ParseVerbosity(os.Getenv(\"BSHARP_VERBOSITY\"))");
        sb.AppendLine("\tentry := " + GoStringLiteral(defaultEntry));
        sb.AppendLine("\tif len(os.Args) > 1 { entry = os.Args[1] }");
        sb.AppendLine("\tif !dispatchTarget(entry) {");
        sb.AppendLine("\t\tfmt.Fprintf(os.Stderr, \"bsharp-go-host: unknown target %q\\n\", entry)");
        sb.AppendLine("\t\tos.Exit(2)");
        sb.AppendLine("\t}");
        sb.AppendLine("\tif rt.GetErrorList().HasErrors() {");
        sb.AppendLine("\t\tfmt.Fprint(os.Stderr, rt.GetErrorList().FormatSummary())");
        sb.AppendLine("\t\tos.Exit(1)");
        sb.AppendLine("\t}");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Reference \"strings\" to keep the import alive when no helper uses it.");
        sb.AppendLine("var _ = strings.ToLower");
    }

    static string BuildGoMod(string runtimeReplacePath) {
        var sb = new StringBuilder();
        sb.AppendLine("module bsharp/generated-host");
        sb.AppendLine();
        sb.AppendLine("go 1.21");
        sb.AppendLine();
        sb.AppendLine("require github.com/simonrozsival/bsharp-host-go v0.0.0");
        sb.AppendLine();
        sb.AppendLine("replace github.com/simonrozsival/bsharp-host-go => " + runtimeReplacePath);
        return sb.ToString();
    }

    static string SanitizeTargetName(string name, HashSet<string> existing) {
        var sb = new StringBuilder("Target_");
        foreach (var c in name) {
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        var candidate = sb.ToString();
        var n = 1;
        while (!existing.Add(candidate)) {
            candidate = sb.ToString() + "_" + n++;
        }
        return candidate;
    }

    static string GoStringLiteral(string? value) {
        if (string.IsNullOrEmpty(value)) return "\"\"";
        var sb = new StringBuilder("\"");
        foreach (var c in value) {
            switch (c) {
                case '\\': sb.Append("\\\\"); break;
                case '"':  sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 0x20) sb.AppendFormat("\\u{0:X4}", (int)c);
                    else sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    static string EscapeForGo(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    internal sealed class EmitReport {
        public PropertiesReport Properties { get; set; } = new();
        public ItemsReport Items { get; set; } = new();
        public TargetsReport Targets { get; set; } = new();
        public string Note { get; set; } =
            "Phase A scaffold. Real bodies emitted for simple targets; complex ones still panic.";
    }
    internal sealed class PropertiesReport {
        public int Total { get; set; }
        public int SupportedLiteral { get; set; }
    }
    internal sealed class ItemsReport {
        public int TotalTypes { get; set; }
        public int TotalItems { get; set; }
        public int SupportedLiteral { get; set; }
    }
    internal sealed class TargetsReport {
        public int Total { get; set; }
        public int RealBody { get; set; }
        public int StubBody { get; set; }
        public SortedDictionary<string, int> UnsupportedReasons { get; set; } = new(StringComparer.Ordinal);
    }
}
