// <auto-generated/> - Go host emitter (foundation scaffolding)
#nullable enable
using Microsoft.Build.Construction;
using Microsoft.Build.Execution;
using System.Text;
using System.Text.Json;

namespace Bsharp.Codegen;

/// <summary>
/// Foundation-only Go host emitter. This is intentionally a thin shell:
/// it loads the project, walks the ProjectInstance, and emits a Go module
/// with stub target bodies plus a self-describing emit-report.json. It is
/// NOT a working build host yet; target bodies panic with
/// runtime.NotImplemented when invoked.
///
/// The point of this scaffold is to make every subsequent emission task
/// fail loudly at codegen time (or at runtime panic) so we can grow real
/// emission piece-by-piece without ever producing silently-wrong Go.
/// </summary>
internal static class GoEmitter {
    public static int Emit(
        ProjectInstance instance,
        string outDir,
        IReadOnlyList<string>? requestedTargets,
        Dictionary<string, string> globalProps,
        string runtimeReplacePath
    ) {
        Directory.CreateDirectory(outDir);
        var report = new EmitReport();

        var mainGo = BuildMainGo(instance, requestedTargets, report);
        var goMod = BuildGoMod(runtimeReplacePath);

        File.WriteAllText(Path.Combine(outDir, "main.go"), mainGo);
        File.WriteAllText(Path.Combine(outDir, "go.mod"), goMod);
        File.WriteAllText(Path.Combine(outDir, "emit-report.json"),
            JsonSerializer.Serialize(report, new JsonSerializerOptions { WriteIndented = true }));

        Console.Error.WriteLine($"codegen: --emit-go wrote main.go ({mainGo.Length} chars), go.mod, emit-report.json to {outDir}");
        Console.Error.WriteLine($"codegen: --emit-go status: {report.Targets.Total} targets ({report.Targets.SupportedStub} stub, {report.Targets.UnsupportedNote} marked unsupported)");
        Console.Error.WriteLine($"codegen: --emit-go NOT a working host yet — target bodies panic at runtime via runtime.NotImplemented.");
        return 0;
    }

    static string BuildMainGo(ProjectInstance instance, IReadOnlyList<string>? requestedTargets, EmitReport report) {
        var sb = new StringBuilder();
        sb.AppendLine("// Code generated by bsharp codegen --emit-go. DO NOT EDIT.");
        sb.AppendLine("//");
        sb.AppendLine("// Foundation scaffold only. Target bodies are NOT implemented; calling");
        sb.AppendLine("// any target will panic via runtime.NotImplemented. Use this file as a");
        sb.AppendLine("// shape reference for the real emitter that will land in follow-up work.");
        sb.AppendLine("package main");
        sb.AppendLine();
        sb.AppendLine("import (");
        sb.AppendLine("\t\"fmt\"");
        sb.AppendLine("\t\"os\"");
        sb.AppendLine("\t\"strings\"");
        sb.AppendLine();
        sb.AppendLine("\trt \"github.com/simonrozsival/bsharp-host-go/runtime\"");
        sb.AppendLine(")");
        sb.AppendLine();

        EmitProperties(sb, instance, report);
        EmitItems(sb, instance, report);
        EmitTargetStubs(sb, instance, report);
        EmitMain(sb, instance, requestedTargets);

        return sb.ToString();
    }

    static void EmitProperties(StringBuilder sb, ProjectInstance instance, EmitReport report) {
        var properties = instance.Properties
            .Where(p => !string.IsNullOrEmpty(p.Name))
            .OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        report.Properties.Total = properties.Length;
        report.Properties.SupportedLiteral = 0;

        sb.AppendLine("// P captures the initial property snapshot. Real codegen will route");
        sb.AppendLine("// dynamic mutations through typed setters; for now it's a value-bag.");
        sb.AppendLine("type properties struct {");
        sb.AppendLine("\textras map[string]string");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("func (p *properties) Get(name string) string {");
        sb.AppendLine("\tif p.extras == nil { return \"\" }");
        sb.AppendLine("\treturn p.extras[strings.ToLower(name)]");
        sb.AppendLine("}");
        sb.AppendLine("func (p *properties) Set(name, value string) {");
        sb.AppendLine("\tif p.extras == nil { p.extras = make(map[string]string) }");
        sb.AppendLine("\tp.extras[strings.ToLower(name)] = value");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("var P = &properties{ extras: map[string]string{");
        foreach (var prop in properties) {
            sb.Append("\t\"").Append(prop.Name.ToLowerInvariant()).Append("\": ");
            sb.Append(GoStringLiteral(prop.EvaluatedValue));
            sb.AppendLine(",");
            report.Properties.SupportedLiteral++;
        }
        sb.AppendLine("}}");
        sb.AppendLine();
    }

    static void EmitItems(StringBuilder sb, ProjectInstance instance, EmitReport report) {
        var byType = instance.Items
            .GroupBy(i => i.ItemType, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        report.Items.TotalTypes = byType.Length;
        report.Items.TotalItems = instance.Items.Count;
        report.Items.SupportedLiteral = 0;

        sb.AppendLine("// I holds typed item lists, keyed by lowercased item type. Generated.");
        sb.AppendLine("type items struct {");
        sb.AppendLine("\tlists map[string][]*rt.Item");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("func (it *items) Get(name string) []*rt.Item {");
        sb.AppendLine("\treturn it.lists[strings.ToLower(name)]");
        sb.AppendLine("}");
        sb.AppendLine("func (it *items) AppendTo(name string, more []*rt.Item) {");
        sb.AppendLine("\tk := strings.ToLower(name)");
        sb.AppendLine("\tit.lists[k] = append(it.lists[k], more...)");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("var I = newItems()");
        sb.AppendLine();
        sb.AppendLine("func newItems() *items {");
        sb.AppendLine("\tit := &items{ lists: map[string][]*rt.Item{} }");
        foreach (var group in byType) {
            sb.Append("\tit.lists[\"").Append(group.Key.ToLowerInvariant()).Append("\"] = []*rt.Item{");
            var any = false;
            foreach (var item in group) {
                if (any) sb.Append(", ");
                sb.Append("rt.NewItem(").Append(GoStringLiteral(item.EvaluatedInclude)).Append(")");
                any = true;
                report.Items.SupportedLiteral++;
            }
            sb.AppendLine("}");
        }
        sb.AppendLine("\treturn it");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitTargetStubs(StringBuilder sb, ProjectInstance instance, EmitReport report) {
        var targets = instance.Targets.Values
            .OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        report.Targets.Total = targets.Length;
        report.Targets.SupportedStub = 0;
        report.Targets.UnsupportedNote = 0;

        sb.AppendLine("// Target stubs. Each panics via runtime.NotImplemented until the real");
        sb.AppendLine("// body emitter lands. Names are sanitized to Go-identifier form.");
        sb.AppendLine();
        var targetIndex = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var nameSet = new HashSet<string>(StringComparer.Ordinal);
        foreach (var target in targets) {
            var ident = SanitizeTargetName(target.Name, nameSet);
            targetIndex[target.Name] = ident;
            sb.Append("func ").Append(ident).Append("() {");
            sb.AppendLine();
            sb.Append("\trt.NotImplemented(").Append(GoStringLiteral(target.Name)).AppendLine(")");
            sb.AppendLine("\tpanic(\"target body not yet emitted: " + EscapeForGo(target.Name) + "\")");
            sb.AppendLine("}");
            sb.AppendLine();
            report.Targets.SupportedStub++;
        }

        sb.AppendLine("// dispatchTarget maps target names to stub functions. Generated.");
        sb.AppendLine("func dispatchTarget(name string) bool {");
        sb.AppendLine("\tswitch strings.ToLower(name) {");
        foreach (var target in targets) {
            sb.Append("\tcase ").Append(GoStringLiteral(target.Name.ToLowerInvariant())).Append(":");
            sb.AppendLine();
            sb.Append("\t\t").Append(targetIndex[target.Name]).AppendLine("()");
            sb.AppendLine("\t\treturn true");
        }
        sb.AppendLine("\t}");
        sb.AppendLine("\treturn false");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitMain(StringBuilder sb, ProjectInstance instance, IReadOnlyList<string>? requestedTargets) {
        var defaultEntry = requestedTargets is { Count: > 0 } ? requestedTargets[0] : (instance.DefaultTargets.FirstOrDefault() ?? "Build");
        sb.AppendLine("func main() {");
        sb.AppendLine("\tentry := " + GoStringLiteral(defaultEntry));
        sb.AppendLine("\tif len(os.Args) > 1 { entry = os.Args[1] }");
        sb.AppendLine("\tif !dispatchTarget(entry) {");
        sb.AppendLine("\t\tfmt.Fprintf(os.Stderr, \"bsharp-go-host: unknown target %q\\n\", entry)");
        sb.AppendLine("\t\tos.Exit(2)");
        sb.AppendLine("\t}");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Reference \"strings\" to keep the import alive when no helper uses it.");
        sb.AppendLine("var _ = strings.ToLower");
    }

    static string BuildGoMod(string runtimeReplacePath) {
        var sb = new StringBuilder();
        sb.AppendLine("module bsharp/generated-host");
        sb.AppendLine();
        sb.AppendLine("go 1.21");
        sb.AppendLine();
        sb.AppendLine("require github.com/simonrozsival/bsharp-host-go v0.0.0");
        sb.AppendLine();
        sb.AppendLine("replace github.com/simonrozsival/bsharp-host-go => " + runtimeReplacePath);
        return sb.ToString();
    }

    static string SanitizeTargetName(string name, HashSet<string> existing) {
        var sb = new StringBuilder("Target_");
        foreach (var c in name) {
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        var candidate = sb.ToString();
        var n = 1;
        while (!existing.Add(candidate)) {
            candidate = sb.ToString() + "_" + n++;
        }
        return candidate;
    }

    static string GoStringLiteral(string? value) {
        if (string.IsNullOrEmpty(value)) return "\"\"";
        var sb = new StringBuilder("\"");
        foreach (var c in value) {
            switch (c) {
                case '\\': sb.Append("\\\\"); break;
                case '"':  sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 0x20) sb.AppendFormat("\\u{0:X4}", (int)c);
                    else sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    static string EscapeForGo(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    internal sealed class EmitReport {
        public PropertiesReport Properties { get; set; } = new();
        public ItemsReport Items { get; set; } = new();
        public TargetsReport Targets { get; set; } = new();
        public string Note { get; set; } =
            "Foundation scaffold only. Target bodies panic; full emit lands in follow-up work.";
    }
    internal sealed class PropertiesReport {
        public int Total { get; set; }
        public int SupportedLiteral { get; set; }
    }
    internal sealed class ItemsReport {
        public int TotalTypes { get; set; }
        public int TotalItems { get; set; }
        public int SupportedLiteral { get; set; }
    }
    internal sealed class TargetsReport {
        public int Total { get; set; }
        public int SupportedStub { get; set; }
        public int UnsupportedNote { get; set; }
    }
}
