// <auto-generated/> - Go host emitter (foundation scaffolding)
#nullable enable
using Microsoft.Build.Construction;
using Microsoft.Build.Execution;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace Bsharp.Codegen;

/// <summary>
/// Foundation-only Go host emitter. This is intentionally a thin shell:
/// it loads the project, walks the ProjectInstance, and emits a Go module
/// with stub target bodies plus a self-describing emit-report.json. It is
/// NOT a working build host yet; target bodies panic with
/// runtime.NotImplemented when invoked.
///
/// The point of this scaffold is to make every subsequent emission task
/// fail loudly at codegen time (or at runtime panic) so we can grow real
/// emission piece-by-piece without ever producing silently-wrong Go.
/// </summary>
internal static class GoEmitter {
    public static int Emit(
        ProjectInstance instance,
        string outDir,
        IReadOnlyList<string>? requestedTargets,
        Dictionary<string, string> globalProps,
        string runtimeReplacePath
    ) {
        Directory.CreateDirectory(outDir);
        var report = new EmitReport();

        var mainGo = BuildMainGo(instance, requestedTargets, report);
        var goMod = BuildGoMod(runtimeReplacePath);

        File.WriteAllText(Path.Combine(outDir, "main.go"), mainGo);
        File.WriteAllText(Path.Combine(outDir, "go.mod"), goMod);
        File.WriteAllText(Path.Combine(outDir, "emit-report.json"),
            JsonSerializer.Serialize(report, new JsonSerializerOptions { WriteIndented = true }));

        Console.Error.WriteLine($"codegen: --emit-go wrote main.go ({mainGo.Length} chars), go.mod, emit-report.json to {outDir}");
        Console.Error.WriteLine($"codegen: --emit-go status: {report.Targets.Total} targets ({report.Targets.RealBody} real-body, {report.Targets.StubBody} stub)");
        Console.Error.WriteLine($"codegen: --emit-go Phase A: complex targets still panic; see emit-report.json for per-reason counts.");
        return 0;
    }

    static string BuildMainGo(ProjectInstance instance, IReadOnlyList<string>? requestedTargets, EmitReport report) {
        var sb = new StringBuilder();
        sb.AppendLine("// Code generated by bsharp codegen --emit-go. DO NOT EDIT.");
        sb.AppendLine("//");
        sb.AppendLine("// Foundation scaffold only. Target bodies are NOT implemented; calling");
        sb.AppendLine("// any target will panic via runtime.NotImplemented. Use this file as a");
        sb.AppendLine("// shape reference for the real emitter that will land in follow-up work.");
        sb.AppendLine("package main");
        sb.AppendLine();
        sb.AppendLine("import (");
        sb.AppendLine("\t\"fmt\"");
        sb.AppendLine("\t\"os\"");
        sb.AppendLine("\t\"strings\"");
        sb.AppendLine();
        sb.AppendLine("\trt \"github.com/simonrozsival/bsharp-host-go/runtime\"");
        sb.AppendLine(")");
        sb.AppendLine();

        EmitProperties(sb, instance, report);
        EmitItems(sb, instance, report);
        EmitTargetStubs(sb, instance, report);
        EmitMain(sb, instance, requestedTargets);

        return sb.ToString();
    }

    static void EmitProperties(StringBuilder sb, ProjectInstance instance, EmitReport report) {
        var properties = instance.Properties
            .Where(p => !string.IsNullOrEmpty(p.Name))
            .OrderBy(p => p.Name, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        report.Properties.Total = properties.Length;
        report.Properties.SupportedLiteral = 0;

        sb.AppendLine("// P captures the initial property snapshot. Real codegen will route");
        sb.AppendLine("// dynamic mutations through typed setters; for now it's a value-bag.");
        sb.AppendLine("type properties struct {");
        sb.AppendLine("\textras map[string]string");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("func (p *properties) Get(name string) string {");
        sb.AppendLine("\tif p.extras == nil { return \"\" }");
        sb.AppendLine("\treturn p.extras[strings.ToLower(name)]");
        sb.AppendLine("}");
        sb.AppendLine("func (p *properties) Set(name, value string) {");
        sb.AppendLine("\tif p.extras == nil { p.extras = make(map[string]string) }");
        sb.AppendLine("\tp.extras[strings.ToLower(name)] = value");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("var P = &properties{ extras: map[string]string{");
        foreach (var prop in properties) {
            sb.Append("\t\"").Append(prop.Name.ToLowerInvariant()).Append("\": ");
            sb.Append(GoStringLiteral(prop.EvaluatedValue));
            sb.AppendLine(",");
            report.Properties.SupportedLiteral++;
        }
        sb.AppendLine("}}");
        sb.AppendLine();
    }

    static void EmitItems(StringBuilder sb, ProjectInstance instance, EmitReport report) {
        var byType = instance.Items
            .GroupBy(i => i.ItemType, StringComparer.OrdinalIgnoreCase)
            .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        report.Items.TotalTypes = byType.Length;
        report.Items.TotalItems = instance.Items.Count;
        report.Items.SupportedLiteral = 0;

        sb.AppendLine("// I holds typed item lists, keyed by lowercased item type. Generated.");
        sb.AppendLine("type items struct {");
        sb.AppendLine("\tlists map[string][]*rt.Item");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("func (it *items) Get(name string) []*rt.Item {");
        sb.AppendLine("\treturn it.lists[strings.ToLower(name)]");
        sb.AppendLine("}");
        sb.AppendLine("func (it *items) AppendTo(name string, more []*rt.Item) {");
        sb.AppendLine("\tk := strings.ToLower(name)");
        sb.AppendLine("\tit.lists[k] = append(it.lists[k], more...)");
        sb.AppendLine("}");
        sb.AppendLine("// RemoveByIdentity removes every item from list `name` whose Identity");
        sb.AppendLine("// matches identity. Used by emitted <ItemGroup><X Remove=\"...\"/></ItemGroup>.");
        sb.AppendLine("func (it *items) RemoveByIdentity(name, identity string) {");
        sb.AppendLine("\tk := strings.ToLower(name)");
        sb.AppendLine("\tlist := it.lists[k]");
        sb.AppendLine("\tif len(list) == 0 { return }");
        sb.AppendLine("\tkeep := list[:0]");
        sb.AppendLine("\tfor _, item := range list {");
        sb.AppendLine("\t\tif item.Identity != identity { keep = append(keep, item) }");
        sb.AppendLine("\t}");
        sb.AppendLine("\tit.lists[k] = keep");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("var I = newItems()");
        sb.AppendLine();
        sb.AppendLine("func newItems() *items {");
        sb.AppendLine("\tit := &items{ lists: map[string][]*rt.Item{} }");
        foreach (var group in byType) {
            sb.Append("\tit.lists[\"").Append(group.Key.ToLowerInvariant()).Append("\"] = []*rt.Item{");
            var any = false;
            foreach (var item in group) {
                if (any) sb.Append(", ");
                sb.Append("rt.NewItem(").Append(GoStringLiteral(item.EvaluatedInclude)).Append(")");
                any = true;
                report.Items.SupportedLiteral++;
            }
            sb.AppendLine("}");
        }
        sb.AppendLine("\treturn it");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitTargetStubs(StringBuilder sb, ProjectInstance instance, EmitReport report) {
        // Preserve declaration order BEFORE we sort for file layout — extender
        // ordering depends on this (MSBuild docs: extenders run in the order
        // their target was declared).
        var targetsInDeclarationOrder = instance.Targets.Values.ToArray();
        var targets = targetsInDeclarationOrder
            .OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase)
            .ToArray();
        var (beforeExtenders, afterExtenders) = BuildExtenderMaps(targetsInDeclarationOrder);
        report.Targets.Total = targets.Length;
        report.Targets.RealBody = 0;
        report.Targets.StubBody = 0;
        report.Targets.UnsupportedReasons = new SortedDictionary<string, int>(StringComparer.Ordinal);

        var targetIndex = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var nameSet = new HashSet<string>(StringComparer.Ordinal);
        foreach (var target in targets) {
            targetIndex[target.Name] = SanitizeTargetName(target.Name, nameSet);
        }

        sb.AppendLine("// Generated target functions. Each target is classified as one of:");
        sb.AppendLine("//   - real-body: emitted from MSBuild XML using runtime.Expand / runtime.EvalCondition");
        sb.AppendLine("//   - stub:      panics via runtime.NotImplemented (Phase A doesn't yet handle the construct)");
        sb.AppendLine("// See emit-report.json for the classification per target.");
        sb.AppendLine();

        foreach (var target in targets) {
            var ident = targetIndex[target.Name];
            var reason = ClassifyTarget(target);
            if (reason == null) {
                EmitRealTargetBody(sb, target, ident, targetIndex, beforeExtenders, afterExtenders);
                report.Targets.RealBody++;
            } else {
                EmitStubTargetBody(sb, target, ident, reason);
                report.Targets.StubBody++;
                report.Targets.UnsupportedReasons.TryGetValue(reason, out var c);
                report.Targets.UnsupportedReasons[reason] = c + 1;
            }
        }

        sb.AppendLine("// dispatchTarget maps target names to functions. Generated.");
        sb.AppendLine("func dispatchTarget(name string) bool {");
        sb.AppendLine("\tswitch strings.ToLower(name) {");
        foreach (var target in targets) {
            sb.Append("\tcase ").Append(GoStringLiteral(target.Name.ToLowerInvariant())).Append(":");
            sb.AppendLine();
            sb.Append("\t\t").Append(targetIndex[target.Name]).AppendLine("()");
            sb.AppendLine("\t\treturn true");
        }
        sb.AppendLine("\t}");
        sb.AppendLine("\treturn false");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitStubTargetBody(StringBuilder sb, ProjectTargetInstance target, string ident, string reason) {
        sb.Append("// ").Append(target.Name).Append(": stub — ").AppendLine(reason);
        sb.Append("func ").Append(ident).AppendLine("() {");
        sb.Append("\trt.NotImplemented(").Append(GoStringLiteral(target.Name)).AppendLine(")");
        sb.AppendLine("\tpanic(\"target body not yet emitted: " + EscapeForGo(target.Name) + " — " + EscapeForGo(reason) + "\")");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    static void EmitRealTargetBody(StringBuilder sb, ProjectTargetInstance target, string ident,
        Dictionary<string, string> targetIndex,
        Dictionary<string, List<string>> beforeExtenders,
        Dictionary<string, List<string>> afterExtenders)
    {
        beforeExtenders.TryGetValue(target.Name, out var befores);
        afterExtenders.TryGetValue(target.Name, out var afters);
        var hasBefores = befores is { Count: > 0 };
        var hasAfters = afters is { Count: > 0 };
        var hasCond = !string.IsNullOrWhiteSpace(target.Condition);
        var hasIO = !string.IsNullOrWhiteSpace(target.Inputs) || !string.IsNullOrWhiteSpace(target.Outputs);

        sb.Append("// ").Append(target.Name).AppendLine(": real body");
        sb.Append("func ").Append(ident).AppendLine("() {");
        sb.Append("\tts := rt.GetTargetState(").Append(GoStringLiteral(target.Name)).AppendLine(")");
        sb.AppendLine("\tif !ts.TryEnter() { return }");

        if (!string.IsNullOrWhiteSpace(target.DependsOnTargets)) {
            var dot = target.DependsOnTargets;
            if (dot.Contains('$')) {
                // Dynamic depends-on: expand the template at runtime and
                // dispatch by name. Order is preserved; duplicates are kept
                // (MSBuild may legitimately re-attempt a target after an
                // intervening mutation — TargetState's TryEnter handles the
                // "already done" short-circuit). Unknown names panic loudly.
                sb.Append("\tfor _, dep := range rt.SplitSemicolon(rt.MustExpand(")
                  .Append(GoStringLiteral(dot))
                  .AppendLine(", P, I, nil)) {");
                sb.AppendLine("\t\tif dep == \"\" { continue }");
                sb.Append("\t\tif !dispatchTarget(dep) { panic(fmt.Sprintf(")
                  .Append(GoStringLiteral("DependsOnTargets: unknown target %q referenced by " + target.Name))
                  .AppendLine(", dep)) }");
                sb.AppendLine("\t}");
            } else {
                foreach (var dep in dot.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)) {
                    if (targetIndex.TryGetValue(dep, out var depIdent)) {
                        sb.Append("\t").Append(depIdent).AppendLine("()")
                          .Append("");
                    }
                }
            }
        }

        // Phase E: before-extenders (literal only — dynamic extender attrs are
        // rejected by ClassifyTarget). They run unconditionally after the
        // depends-on chain, regardless of this target's condition.
        if (hasBefores) {
            foreach (var be in befores!) {
                if (targetIndex.TryGetValue(be, out var beIdent)) {
                    sb.Append("\t").Append(beIdent).AppendLine("()");
                }
            }
        }

        if (!hasBefores && !hasAfters) {
            // Fast path: no extenders, keep the existing early-return shape.
            if (hasCond) {
                sb.Append("\tif !rt.MustEvalCondition(").Append(GoStringLiteral(target.Condition)).AppendLine(", P, I) { ts.MarkSkipped(); return }");
            }
            EmitTargetBodyOrIncremental(sb, target, hasIO);
            sb.AppendLine("\tts.MarkDone()");
        } else {
            // Extender path: keep TargetState in `running` until after-extenders
            // finish. Calling MarkSkipped before after-extenders would reset
            // state to pending and allow an after-extender's DependsOnTargets to
            // immediately re-enter the same target, producing recursion that
            // MSBuild avoids.
            if (hasCond) {
                sb.Append("\tcondOk := rt.MustEvalCondition(").Append(GoStringLiteral(target.Condition)).AppendLine(", P, I)");
                sb.AppendLine("\tif condOk {");
            }
            // Body emitted at \t (child emitters hardcode \t indent). When the
            // condition wraps the body, the resulting code is visually
            // mis-indented but valid Go.
            EmitTargetBodyOrIncremental(sb, target, hasIO);
            sb.AppendLine("\tts.MarkDone()");
            if (hasCond) {
                sb.AppendLine("\t}");
            }
            if (hasAfters) {
                foreach (var ae in afters!) {
                    if (targetIndex.TryGetValue(ae, out var aeIdent)) {
                        sb.Append("\t").Append(aeIdent).AppendLine("()");
                    }
                }
            }
            if (hasCond) {
                sb.AppendLine("\tif !condOk { ts.MarkSkipped() }");
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    // EmitTargetBodyOrIncremental emits either the unconditional body (started
    // → children → finished) or the Phase D incremental shape:
    //
    //     if !rt.IsUpToDate(name, inputs, outputs) {
    //         started := ...; <children>; finished := ...
    //     } else {
    //         rt.Log.TargetUpToDate(name)
    //         <output inference: PG/IG only — task <Output/> is rejected at classifier>
    //     }
    //
    // MarkDone() is emitted by the caller, AFTER this block, regardless of
    // branch. Up-to-date is a successful terminal completion; downstream
    // targets must not re-run the target.
    static void EmitTargetBodyOrIncremental(StringBuilder sb, ProjectTargetInstance target, bool hasIO) {
        if (hasIO) {
            sb.Append("\tif !rt.IsUpToDate(").Append(GoStringLiteral(target.Name))
              .Append(", rt.MustExpand(").Append(GoStringLiteral(target.Inputs ?? "")).Append(", P, I, nil)")
              .Append(", rt.MustExpand(").Append(GoStringLiteral(target.Outputs ?? "")).AppendLine(", P, I, nil)) {");
            sb.Append("\tstarted := rt.Log.TargetStarted(").Append(GoStringLiteral(target.Name)).AppendLine(")");
            EmitTargetChildren(sb, target);
            sb.Append("\trt.Log.TargetFinished(").Append(GoStringLiteral(target.Name)).AppendLine(", started)");
            sb.AppendLine("\t} else {");
            sb.Append("\trt.Log.TargetUpToDate(").Append(GoStringLiteral(target.Name)).AppendLine(")");
            EmitTargetChildrenForUpToDateSkip(sb, target);
            sb.AppendLine("\t}");
        } else {
            sb.Append("\tstarted := rt.Log.TargetStarted(").Append(GoStringLiteral(target.Name)).AppendLine(")");
            EmitTargetChildren(sb, target);
            sb.Append("\trt.Log.TargetFinished(").Append(GoStringLiteral(target.Name)).AppendLine(", started)");
        }
    }

    static void EmitTargetChildren(StringBuilder sb, ProjectTargetInstance target) {
        foreach (var child in target.Children) {
            switch (child) {
                case ProjectTaskInstance task:
                    EmitLocalTaskCall(sb, target, task);
                    break;
                case ProjectPropertyGroupTaskInstance pg:
                    EmitPropertyGroup(sb, pg);
                    break;
                case ProjectItemGroupTaskInstance ig:
                    EmitItemGroup(sb, ig);
                    break;
            }
        }
    }

    // EmitTargetChildrenForUpToDateSkip emits the "output inference" pass
    // MSBuild applies when a target is skipped as up-to-date: PropertyGroup
    // and ItemGroup mutations are re-applied so downstream targets see the
    // same state they would see if the target had executed. Tasks are
    // intentionally NOT emitted: targets containing a task with <Output/> are
    // rejected at classifier level (task-has-outputs:X), and tasks without
    // outputs have no state to infer.
    static void EmitTargetChildrenForUpToDateSkip(StringBuilder sb, ProjectTargetInstance target) {
        foreach (var child in target.Children) {
            switch (child) {
                case ProjectPropertyGroupTaskInstance pg:
                    EmitPropertyGroup(sb, pg);
                    break;
                case ProjectItemGroupTaskInstance ig:
                    EmitItemGroup(sb, ig);
                    break;
            }
        }
    }



    static void EmitPropertyGroup(StringBuilder sb, ProjectPropertyGroupTaskInstance pg) {
        var hasOuterCond = !string.IsNullOrWhiteSpace(pg.Condition);
        var indent = "\t";
        if (hasOuterCond) {
            sb.Append(indent).Append("if rt.MustEvalCondition(").Append(GoStringLiteral(pg.Condition)).AppendLine(", P, I) {");
            indent = "\t\t";
        }
        foreach (var prop in pg.Properties) {
            var hasCond = !string.IsNullOrWhiteSpace(prop.Condition);
            if (hasCond) {
                sb.Append(indent).Append("if rt.MustEvalCondition(").Append(GoStringLiteral(prop.Condition)).AppendLine(", P, I) {");
                sb.Append(indent).Append("\tP.Set(").Append(GoStringLiteral(prop.Name)).Append(", rt.MustExpand(")
                  .Append(GoStringLiteral(prop.Value)).AppendLine(", P, I, nil))");
                sb.Append(indent).AppendLine("}");
            } else {
                sb.Append(indent).Append("P.Set(").Append(GoStringLiteral(prop.Name)).Append(", rt.MustExpand(")
                  .Append(GoStringLiteral(prop.Value)).AppendLine(", P, I, nil))");
            }
        }
        if (hasOuterCond) sb.AppendLine("\t}");
    }

    static void EmitItemGroup(StringBuilder sb, ProjectItemGroupTaskInstance ig) {
        var hasOuterCond = !string.IsNullOrWhiteSpace(ig.Condition);
        var indent = "\t";
        if (hasOuterCond) {
            sb.Append(indent).Append("if rt.MustEvalCondition(").Append(GoStringLiteral(ig.Condition)).AppendLine(", P, I) {");
            indent = "\t\t";
        }
        foreach (var item in ig.Items) {
            EmitItemGroupChild(sb, item, indent);
        }
        if (hasOuterCond) sb.AppendLine("\t}");
    }

    static void EmitItemGroupChild(StringBuilder sb, ProjectItemGroupTaskItemInstance item, string indent) {
        var hasCond = !string.IsNullOrWhiteSpace(item.Condition);
        var bodyIndent = indent;
        if (hasCond) {
            sb.Append(indent).Append("if rt.MustEvalCondition(").Append(GoStringLiteral(item.Condition)).AppendLine(", P, I) {");
            bodyIndent = indent + "\t";
        }

        var include = item.Include ?? "";
        var remove = item.Remove ?? "";
        var itemType = item.ItemType;

        if (include.Length > 0) {
            var kind = ClassifyItemIncludeSpec(include);
            if (kind == ItemIncludeKind.ItemListCopy) {
                var sourceType = include.Trim().Substring(2, include.Trim().Length - 3).Trim();
                sb.Append(bodyIndent).Append("for _, src := range I.Get(").Append(GoStringLiteral(sourceType)).AppendLine(") {");
                sb.Append(bodyIndent).AppendLine("\titem := src.Clone()");
                EmitItemMetadata(sb, item, bodyIndent + "\t", "item");
                sb.Append(bodyIndent).Append("\tI.AppendTo(").Append(GoStringLiteral(itemType)).AppendLine(", []*rt.Item{item})");
                sb.Append(bodyIndent).AppendLine("}");
            } else {
                // Literal/expansion path: expand, split, create items with metadata.
                sb.Append(bodyIndent).Append("for _, id := range rt.SplitSemicolon(rt.MustExpand(")
                  .Append(GoStringLiteral(include)).AppendLine(", P, I, nil)) {");
                sb.Append(bodyIndent).AppendLine("\titem := rt.NewItem(id)");
                EmitItemMetadata(sb, item, bodyIndent + "\t", "item");
                sb.Append(bodyIndent).Append("\tI.AppendTo(").Append(GoStringLiteral(itemType)).AppendLine(", []*rt.Item{item})");
                sb.Append(bodyIndent).AppendLine("}");
            }
        } else if (remove.Length > 0) {
            sb.Append(bodyIndent).Append("for _, id := range rt.SplitSemicolon(rt.MustExpand(")
              .Append(GoStringLiteral(remove)).AppendLine(", P, I, nil)) {");
            sb.Append(bodyIndent).Append("\tI.RemoveByIdentity(").Append(GoStringLiteral(itemType)).AppendLine(", id)");
            sb.Append(bodyIndent).AppendLine("}");
        }

        if (hasCond) sb.Append(indent).AppendLine("}");
    }

    static void EmitItemMetadata(StringBuilder sb, ProjectItemGroupTaskItemInstance item, string indent, string itemVar) {
        foreach (var meta in item.Metadata) {
            var hasMetaCond = !string.IsNullOrWhiteSpace(meta.Condition);
            if (hasMetaCond) {
                sb.Append(indent).Append("if rt.MustEvalCondition(").Append(GoStringLiteral(meta.Condition)).AppendLine(", P, I) {");
                sb.Append(indent).Append("\t").Append(itemVar).Append(".SetMetadata(").Append(GoStringLiteral(meta.Name))
                  .Append(", rt.MustExpand(").Append(GoStringLiteral(meta.Value)).AppendLine(", P, I, nil))");
                sb.Append(indent).AppendLine("}");
            } else {
                sb.Append(indent).Append(itemVar).Append(".SetMetadata(").Append(GoStringLiteral(meta.Name))
                  .Append(", rt.MustExpand(").Append(GoStringLiteral(meta.Value)).AppendLine(", P, I, nil))");
            }
        }
    }

    static void EmitLocalTaskCall(StringBuilder sb, ProjectTargetInstance target, ProjectTaskInstance task) {
        // CallTarget is special — it doesn't have a runtime helper; it
        // dispatches to other targets emitted in this same file.
        if (string.Equals(task.Name, "CallTarget", StringComparison.OrdinalIgnoreCase)) {
            EmitCallTargetTask(sb, target, task);
            return;
        }

        var fn = LocalTaskGoFunc(task.Name);
        if (fn == null) {
            sb.Append("\trt.NotImplemented(").Append(GoStringLiteral(target.Name + ":" + task.Name)).AppendLine(")");
            return;
        }

        if (!string.IsNullOrWhiteSpace(task.Condition)) {
            sb.Append("\tif rt.MustEvalCondition(").Append(GoStringLiteral(task.Condition)).AppendLine(", P, I) {");
        }

        sb.Append("\tif err := rt.").Append(fn).Append("(rt.NewParamList(");
        var first = true;
        foreach (var param in task.Parameters) {
            if (!first) sb.Append(", ");
            first = false;
            sb.Append("rt.Param{Key: ").Append(GoStringLiteral(param.Key))
              .Append(", Value: rt.MustExpand(").Append(GoStringLiteral(param.Value)).Append(", P, I, nil)}");
        }
        sb.Append("));");

        // Tasks that take ItemBag/PropertyBag come in two flavors: with or
        // without <Output/> bindings. If there are outputs we construct an
        // *OutputList literal; otherwise pass nil. PropertyBag is always
        // available so property-bound outputs can be written back to P.
        if (TaskNeedsItemBag(task.Name)) {
            sb.Length -= 2;
            sb.Append(", ").Append(EmitTaskOutputList(task)).Append(", I, P);");
        }
        sb.AppendLine(" err != nil { rt.GetErrorList().Add(\"" + EscapeForGo(target.Name) + "\", err) }");

        if (!string.IsNullOrWhiteSpace(task.Condition)) {
            sb.AppendLine("\t}");
        }
    }

    // EmitTaskOutputList emits the second argument to a task helper —
    // either `nil` (no <Output/> children) or `rt.NewOutputList(rt.Output{...})`
    // populated with the task's output bindings (both item and property).
    static string EmitTaskOutputList(ProjectTaskInstance task) {
        if (task.Outputs.Count == 0) return "nil";
        var sb = new StringBuilder();
        sb.Append("rt.NewOutputList(");
        var first = true;
        foreach (var o in task.Outputs) {
            if (!first) sb.Append(", ");
            first = false;
            switch (o) {
                case ProjectTaskOutputItemInstance oi:
                    sb.Append("rt.Output{Key: ").Append(GoStringLiteral(oi.TaskParameter))
                      .Append(", ItemName: ").Append(GoStringLiteral(oi.ItemType))
                      .Append("}");
                    break;
                case ProjectTaskOutputPropertyInstance op:
                    sb.Append("rt.Output{Key: ").Append(GoStringLiteral(op.TaskParameter))
                      .Append(", PropertyName: ").Append(GoStringLiteral(op.PropertyName))
                      .Append("}");
                    break;
                default:
                    // Unknown output binding type — emit a dummy entry so the
                    // generated source still compiles but the runtime will
                    // ignore it.
                    sb.Append("rt.Output{}");
                    break;
            }
        }
        sb.Append(")");
        return sb.ToString();
    }

    // EmitCallTargetTask emits a `<CallTarget Targets="..." />` task as a
    // runtime loop that splits the expanded Targets attribute and dispatches
    // each non-empty name through dispatchTarget. Mirrors the dynamic-
    // DependsOnTargets emission. RunEachTargetSeparately and ContinueOnError
    // are ignored (single-pass sequential dispatch — the runtime currently
    // panics on any task error anyway).
    static void EmitCallTargetTask(StringBuilder sb, ProjectTargetInstance target, ProjectTaskInstance task) {
        if (!string.IsNullOrWhiteSpace(task.Condition)) {
            sb.Append("\tif rt.MustEvalCondition(").Append(GoStringLiteral(task.Condition)).AppendLine(", P, I) {");
        }
        var targetsAttr = task.Parameters.TryGetValue("Targets", out var t) ? t : "";
        sb.Append("\t\tfor _, _ct := range rt.SplitSemicolon(rt.MustExpand(")
          .Append(GoStringLiteral(targetsAttr)).AppendLine(", P, I, nil)) {");
        sb.AppendLine("\t\t\tif _ct == \"\" { continue }");
        sb.Append("\t\t\tif !dispatchTarget(_ct) { panic(\"CallTarget: unknown target referenced by ")
          .Append(EscapeForGo(target.Name)).AppendLine("\") }");
        sb.AppendLine("\t\t}");
        if (!string.IsNullOrWhiteSpace(task.Condition)) {
            sb.AppendLine("\t}");
        }
    }

    // ClassifyTarget returns null if the target can be emitted with a real
    // body, or a short reason string otherwise.
    static string? ClassifyTarget(ProjectTargetInstance target) {
        if (ContainsBatching(target.Inputs) || ContainsBatching(target.Outputs)) {
            return "target-batching";
        }
        if (!IsSimpleExpressionTemplate(target.Inputs)) return "target-inputs-complex";
        if (!IsSimpleExpressionTemplate(target.Outputs)) return "target-outputs-complex";
        if (HasDynamicExtenderAttr(target.BeforeTargets) || HasDynamicExtenderAttr(target.AfterTargets)) {
            // Dynamic Before/AfterTargets ($/@/% in the attribute) would require
            // runtime extender registration, which Phase E doesn't model.
            return "before-after-dynamic";
        }
        if (!string.IsNullOrWhiteSpace(target.DependsOnTargets)) {
            var (ok, reason) = IsSimpleDependsOnTargetsTemplate(target.DependsOnTargets);
            if (!ok) return reason!;
        }
        if (!IsSimpleConditionTemplate(target.Condition)) {
            return "complex-target-condition";
        }
        foreach (var child in target.Children) {
            switch (child) {
                case ProjectTaskInstance task:
                    if (string.Equals(task.Name, "CallTarget", StringComparison.OrdinalIgnoreCase)) {
                        // CallTarget has no <Output/> bindings worth modelling;
                        // its only effect is the side-effect of dispatching
                        // the listed targets. We accept any condition that
                        // passes the standard simple-condition check, and any
                        // Targets expression that passes IsSimpleExpression.
                        if (!IsSimpleConditionTemplate(task.Condition)) return "complex-task-condition";
                        if (task.Parameters.TryGetValue("Targets", out var ctTargets)) {
                            if (!IsSimpleExpressionTemplate(ctTargets)) return "complex-task-param:CallTarget.Targets";
                            if (ContainsBatching(ctTargets)) return "task-batching";
                        }
                        break;
                    }
                    if (LocalTaskGoFunc(task.Name) == null) return "task:" + task.Name;
                    if (task.Outputs.Count > 0) {
                        // Both item-list and property outputs are wired
                        // through OutputList in the runtime helpers. Reject
                        // any task that isn't on the OutputCapableLocalTasks
                        // whitelist, and any output binding whose target
                        // ItemName/PropertyName isn't a simple identifier.
                        if (!OutputCapableLocalTasks.Contains(task.Name)) return "task-has-outputs:" + task.Name;
                        foreach (var output in task.Outputs) {
                            switch (output) {
                                case ProjectTaskOutputItemInstance oi:
                                    if (!IsSimpleIdentifierName(oi.ItemType)) return "task-output-complex-itemtype:" + task.Name;
                                    break;
                                case ProjectTaskOutputPropertyInstance op:
                                    if (!IsSimpleIdentifierName(op.PropertyName)) return "task-output-complex-propname:" + task.Name;
                                    break;
                                default:
                                    return "task-output-unknown:" + task.Name;
                            }
                        }
                    }
                    if (!IsSimpleConditionTemplate(task.Condition)) return "complex-task-condition";
                    foreach (var p in task.Parameters) {
                        if (!IsSimpleExpressionTemplate(p.Value)) return "complex-task-param:" + task.Name + "." + p.Key;
                        if (ContainsBatching(p.Value)) return "task-batching";
                    }
                    break;
                case ProjectPropertyGroupTaskInstance pg:
                    var pgReason = ClassifyPropertyGroup(pg);
                    if (pgReason != null) return pgReason;
                    break;
                case ProjectItemGroupTaskInstance ig:
                    var igReason = ClassifyItemGroup(ig);
                    if (igReason != null) return igReason;
                    break;
                case ProjectOnErrorInstance:
                    return "on-error";
                default:
                    return "unknown-target-child";
            }
        }
        return null;
    }

    static string? ClassifyPropertyGroup(ProjectPropertyGroupTaskInstance pg) {
        if (!IsSimpleConditionTemplate(pg.Condition)) return "pg-complex-condition";
        foreach (var prop in pg.Properties) {
            if (ContainsBatching(prop.Value)) return "pg-batching";
            if (ContainsBatching(prop.Condition)) return "pg-batching";
            if (!IsSimpleConditionTemplate(prop.Condition)) return "pg-complex-prop-condition";
            if (!IsSimpleExpressionTemplate(prop.Value)) return "pg-complex-prop-value";
            if (!IsSimpleIdentifierName(prop.Name)) return "pg-complex-prop-name";
        }
        return null;
    }

    static string? ClassifyItemGroup(ProjectItemGroupTaskInstance ig) {
        if (!IsSimpleConditionTemplate(ig.Condition)) return "ig-complex-condition";
        foreach (var item in ig.Items) {
            if (!IsSimpleIdentifierName(item.ItemType)) return "ig-complex-item-type";
            if (!IsSimpleConditionTemplate(item.Condition)) return "ig-complex-item-condition";
            // Reject advanced item attributes that we don't model.
            if (!string.IsNullOrEmpty(item.Exclude)) return "ig-exclude-not-supported";
            if (!string.IsNullOrEmpty(item.KeepDuplicates)) return "ig-keep-duplicates-not-supported";
            if (!string.IsNullOrEmpty(item.KeepMetadata)) return "ig-keep-metadata-not-supported";
            if (!string.IsNullOrEmpty(item.RemoveMetadata)) return "ig-remove-metadata-not-supported";
            if (!string.IsNullOrEmpty(item.MatchOnMetadata)) return "ig-match-metadata-not-supported";

            var include = item.Include ?? "";
            var remove = item.Remove ?? "";
            if (include.Length > 0 && remove.Length > 0) return "ig-include-and-remove";
            if (include.Length == 0 && remove.Length == 0) return "ig-empty-include-remove";

            var spec = include.Length > 0 ? include : remove;
            if (ContainsBatching(spec)) return "ig-spec-batching";
            if (ContainsGlobChar(spec)) return "ig-spec-glob-not-supported";
            // Classify the include/remove spec.
            if (include.Length > 0) {
                var includeKind = ClassifyItemIncludeSpec(include);
                if (includeKind == ItemIncludeKind.Unsupported) return "ig-include-complex";
            } else {
                if (!IsSimpleExpressionTemplate(remove)) return "ig-remove-complex";
                if (remove.Contains("@(", StringComparison.Ordinal)) return "ig-remove-item-ref-not-supported";
            }

            foreach (var meta in item.Metadata) {
                if (ContainsBatching(meta.Value)) return "ig-meta-batching";
                if (!IsSimpleConditionTemplate(meta.Condition)) return "ig-complex-meta-condition";
                if (!IsSimpleExpressionTemplate(meta.Value)) return "ig-complex-meta-value";
                if (!IsSimpleIdentifierName(meta.Name)) return "ig-complex-meta-name";
            }
        }
        return null;
    }

    // ItemIncludeKind classifies the syntactic shape of an Include attribute
    // so the emitter can pick the right runtime call:
    //   - Literal: no @() refs at all; expand + split + new items
    //   - ItemListCopy: exactly one @(SimpleType) reference; clone source items
    //   - Unsupported: anything else (mixed, transforms, etc.)
    enum ItemIncludeKind { Literal, ItemListCopy, Unsupported }

    static ItemIncludeKind ClassifyItemIncludeSpec(string include) {
        if (string.IsNullOrEmpty(include)) return ItemIncludeKind.Literal;
        var trimmed = include.Trim();
        // Exactly @(SimpleIdent)
        if (trimmed.StartsWith("@(", StringComparison.Ordinal) && trimmed.EndsWith(")", StringComparison.Ordinal)) {
            var inner = trimmed.Substring(2, trimmed.Length - 3);
            // No transforms or custom separators in the supported form.
            if (!inner.Contains("->", StringComparison.Ordinal) && !inner.Contains(",", StringComparison.Ordinal)
                && IsSimpleIdentifierName(inner.Trim())) {
                return ItemIncludeKind.ItemListCopy;
            }
            return ItemIncludeKind.Unsupported;
        }
        // No @() at all → simple literal/expansion.
        if (!include.Contains("@(", StringComparison.Ordinal)) {
            if (IsSimpleExpressionTemplate(include)) return ItemIncludeKind.Literal;
            return ItemIncludeKind.Unsupported;
        }
        return ItemIncludeKind.Unsupported;
    }

    static bool IsSimpleIdentifierName(string? name) {
        if (string.IsNullOrEmpty(name)) return false;
        foreach (var c in name) {
            if (!(char.IsLetterOrDigit(c) || c == '_' || c == '-')) return false;
        }
        return true;
    }

    static bool ContainsGlobChar(string? s) {
        if (string.IsNullOrEmpty(s)) return false;
        // A `*` or `?` outside quotes signals a glob the emitter does not expand.
        // We don't attempt to honor quoting because $(X) values rarely embed *.
        return s.IndexOfAny(new[] { '*', '?' }) >= 0;
    }

    // LocalTaskGoFunc maps an MSBuild task name to the Go runtime helper name.
    // Returns null for tasks we don't have a local implementation for yet.
    // Matching is case-insensitive — MSBuild treats task names that way and
    // SDK sources use both "NETSdkError" and "NetSdkError" in different files.
    static readonly Dictionary<string, string> _localTaskGoFunc = new(StringComparer.OrdinalIgnoreCase) {
        { "Message", "Message" },
        { "Warning", "Warning" },
        { "Error",   "Error" },
        { "MakeDir", "MakeDir" },
        { "RemoveDir", "RemoveDir" },
        { "Touch",   "Touch" },
        { "Delete",  "Delete" },
        { "Copy",    "Copy" },
        { "WriteLinesToFile", "WriteLinesToFile" },
        { "ReadLinesFromFile", "ReadLinesFromFile" },
        { "Hash", "Hash" },
        { "ConvertToAbsolutePath", "ConvertToAbsolutePath" },
        { "NETSdkError", "NETSdkError" },
        { "NETSdkWarning", "NETSdkWarning" },
        { "NETSdkInformation", "NETSdkInformation" },
        { "MSBuildInternalMessage", "MSBuildInternalMessage" },
    };
    static string? LocalTaskGoFunc(string taskName) =>
        _localTaskGoFunc.TryGetValue(taskName, out var fn) ? fn : null;

    // TaskNeedsItemBag returns true for tasks whose Go signature has the
    // shape (ParamList, *OutputList, ItemBag, PropertyBag). The emitter
    // appends ", outputs, I, P" to the call site for these. Tasks NOT in
    // this set (Message/Warning/Error/WriteLinesToFile/NETSdk*) take only
    // ParamList.
    static readonly HashSet<string> _tasksNeedingItemBag = new(StringComparer.OrdinalIgnoreCase) {
        "MakeDir", "RemoveDir", "Touch", "Delete", "Copy",
        "ReadLinesFromFile", "Hash", "ConvertToAbsolutePath",
    };
    static bool TaskNeedsItemBag(string taskName) => _tasksNeedingItemBag.Contains(taskName);

    // OutputCapableLocalTasks names the tasks whose runtime helper already
    // accepts an *OutputList and writes results into ItemBag and/or
    // PropertyBag. We wire up both <Output ItemName="..."/> and
    // <Output PropertyName="..."/> bindings for these.
    static readonly HashSet<string> OutputCapableLocalTasks = new(StringComparer.OrdinalIgnoreCase) {
        "Copy", "ReadLinesFromFile", "MakeDir", "RemoveDir", "Touch", "Delete",
        "Hash", "ConvertToAbsolutePath",
    };

    // IsSimpleExpressionTemplate returns true if `template` only uses constructs
    // the runtime.Expand evaluator handles in Phase A+B+G: literals, $(X),
    // $(X.Method(args)) chains with whitelisted methods and simple args,
    // $([MSBuild]::F(args)) supported intrinsics, @(Y) (no transforms),
    // and %(Z).
    static bool IsSimpleExpressionTemplate(string? template) {
        if (string.IsNullOrEmpty(template)) return true;
        for (int i = 0; i < template.Length; i++) {
            var c = template[i];
            if (c == '$' || c == '@' || c == '%') {
                if (i + 1 >= template.Length || template[i + 1] != '(') continue;
                var end = FindMatchingParenQuoteAware(template, i + 1);
                if (end < 0) return false;
                var inner = template.Substring(i + 2, end - i - 2);
                if (c == '$') {
                    if (!IsSimpleExpressionInner(inner)) return false;
                } else if (c == '@') {
                    if (inner.Contains("->")) return false;
                    // Allow @(X) and @(X, 'sep'); reject anything else.
                    var parts = SplitArgsQuoteAware(inner);
                    if (parts.Length == 0) return false;
                    if (!IsSimpleIdentifierName(parts[0].Trim())) return false;
                    if (parts.Length == 2) {
                        var sep = parts[1].Trim();
                        if (sep.Length < 2) return false;
                        var q = sep[0];
                        if ((q != '\'' && q != '"') || sep[sep.Length - 1] != q) return false;
                    } else if (parts.Length != 1) {
                        return false;
                    }
                }
                i = end;
            }
        }
        return true;
    }

    // IsSimpleExpressionInner accepts either a Phase A/B property expression
    // (bare identifier or whitelisted method chain on a property) OR a Phase G
    // [TypeName]::Member(args?) call with supported type+member + simple args.
    // Mirrors what the Go runtime's Expand evaluator accepts inside `$(...)`.
    static bool IsSimpleExpressionInner(string inner) {
        var trimmed = inner.Trim();
        if (trimmed.Length > 0 && trimmed[0] == '[') {
            return IsSimpleIntrinsicCall(trimmed);
        }
        // Anything else containing `[` or `:` past the leading char is an
        // unsupported intrinsic or indexer construct we haven't modelled.
        if (inner.IndexOfAny(new[] { '[', ':' }) >= 0) return false;
        return IsSimplePropertyExpression(inner);
    }

    // IsSimpleIntrinsicCall validates the shape `[TypeName]::Member(args?)`.
    // Type+member must appear in IntrinsicMembers (mirrors the runtime
    // dispatch in EvalIntrinsic). Member may be parameterless (static
    // property like `[System.IO.Path]::DirectorySeparatorChar`).
    static bool IsSimpleIntrinsicCall(string s) {
        if (s.Length < 2 || s[0] != '[') return false;
        var closeBracket = s.IndexOf(']');
        if (closeBracket <= 1) return false;
        var typeName = s.Substring(1, closeBracket - 1).Trim();
        if (!IntrinsicMembers.ContainsKey(typeName)) return false;
        var afterBracket = s.Substring(closeBracket + 1);
        if (!afterBracket.StartsWith("::", StringComparison.Ordinal)) return false;
        var rest = afterBracket.Substring(2);
        int nameEnd = 0;
        while (nameEnd < rest.Length && (char.IsLetterOrDigit(rest[nameEnd]) || rest[nameEnd] == '_')) nameEnd++;
        if (nameEnd == 0) return false;
        var member = rest.Substring(0, nameEnd);
        var supportedMembers = IntrinsicMembers[typeName];
        var memberSpec = supportedMembers.FirstOrDefault(m => m.Name.Equals(member, StringComparison.OrdinalIgnoreCase));
        if (memberSpec.Name == null) return false;
        var tail = rest.Substring(nameEnd);
        if (tail.Length == 0) {
            // Property-style access (no parens).
            return !memberSpec.RequiresArgs;
        }
        if (tail[0] != '(') return false;
        var close = FindMatchingParenQuoteAware(tail, 0);
        if (close < 0) return false;
        if (tail.Substring(close + 1).Trim().Length != 0) return false;
        var argsStr = tail.Substring(1, close - 1);
        return AreSimpleMSBuildIntrinsicArgs(argsStr);
    }

    readonly struct IntrinsicMember {
        public string Name { get; init; }
        public bool RequiresArgs { get; init; }
    }

    // IntrinsicMembers mirrors the runtime EvalIntrinsic dispatch (see
    // msbuild_intrinsics.go). When adding a new member to the runtime,
    // add it here too. Property-style members (no parens) have
    // RequiresArgs=false.
    static readonly Dictionary<string, IntrinsicMember[]> IntrinsicMembers =
        new(StringComparer.OrdinalIgnoreCase) {
            ["MSBuild"] = new IntrinsicMember[] {
                new() { Name = "VersionEquals", RequiresArgs = true },
                new() { Name = "VersionGreaterThan", RequiresArgs = true },
                new() { Name = "VersionGreaterThanOrEquals", RequiresArgs = true },
                new() { Name = "VersionLessThan", RequiresArgs = true },
                new() { Name = "VersionLessThanOrEquals", RequiresArgs = true },
                new() { Name = "IsOSPlatform", RequiresArgs = true },
                new() { Name = "IsOsPlatform", RequiresArgs = true },
                new() { Name = "ValueOrDefault", RequiresArgs = true },
                new() { Name = "Escape", RequiresArgs = true },
                new() { Name = "EnsureTrailingSlash", RequiresArgs = true },
                new() { Name = "MakeRelative", RequiresArgs = true },
                new() { Name = "NormalizePath", RequiresArgs = true },
                new() { Name = "NormalizeDirectory", RequiresArgs = true },
            },
            ["System.IO.Path"] = new IntrinsicMember[] {
                new() { Name = "Combine", RequiresArgs = true },
                new() { Name = "GetFullPath", RequiresArgs = true },
                new() { Name = "GetFileName", RequiresArgs = true },
                new() { Name = "GetFileNameWithoutExtension", RequiresArgs = true },
                new() { Name = "GetExtension", RequiresArgs = true },
                new() { Name = "GetDirectoryName", RequiresArgs = true },
                new() { Name = "IsPathRooted", RequiresArgs = true },
                new() { Name = "ChangeExtension", RequiresArgs = true },
                new() { Name = "DirectorySeparatorChar", RequiresArgs = false },
                new() { Name = "PathSeparator", RequiresArgs = false },
                new() { Name = "AltDirectorySeparatorChar", RequiresArgs = false },
            },
        };

    // AreSimpleMSBuildIntrinsicArgs splits `argsStr` on top-level commas and
    // checks each argument is either a quoted string (whose interior may
    // itself contain only simple $() references), a single $(SimpleProp)
    // expansion, or a bare literal (digits/dots/identifier chars — used for
    // bare version literals like `5.0`). Anything else fails.
    static bool AreSimpleMSBuildIntrinsicArgs(string argsStr) {
        if (string.IsNullOrWhiteSpace(argsStr)) return true;
        var depth = 0;
        char quote = '\0';
        int start = 0;
        var parts = new List<string>();
        for (int i = 0; i < argsStr.Length; i++) {
            var c = argsStr[i];
            if (quote != '\0') {
                if (c == quote) quote = '\0';
                continue;
            }
            switch (c) {
                case '\'': case '"': quote = c; break;
                case '(': depth++; break;
                case ')': depth--; break;
                case ',':
                    if (depth == 0) {
                        parts.Add(argsStr.Substring(start, i - start));
                        start = i + 1;
                    }
                    break;
            }
        }
        if (quote != '\0' || depth != 0) return false;
        parts.Add(argsStr.Substring(start));
        foreach (var raw in parts) {
            if (!IsSimpleMSBuildIntrinsicArg(raw.Trim())) return false;
        }
        return true;
    }

    static bool IsSimpleMSBuildIntrinsicArg(string arg) {
        if (arg.Length == 0) return true;
        if ((arg[0] == '\'' || arg[0] == '"' || arg[0] == '`') && arg.Length >= 2 && arg[arg.Length - 1] == arg[0]) {
            // Inside a quoted intrinsic arg, only `$(SimpleProp)` references
            // and literal text are allowed — mirrors splitIntrinsicArgs ->
            // resolveIntrinsicArg in the runtime.
            return AreSimpleExpansionsOnly(arg.Substring(1, arg.Length - 2));
        }
        // Bare unquoted arg: same shape rules as inside a quote — every
        // expansion must be a simple property expression / supported intrinsic;
        // mixed with literal text is fine. Reject `@()` / `%()` because the
        // runtime resolver only passes an emptyItemBag.
        if (arg.IndexOfAny(new[] { '\'', '"', '`' }) >= 0) return false;
        return AreSimpleExpansionsOnly(arg);
    }

    // AreSimpleExpansionsOnly walks a string and ensures that every `$(...)`
    // expansion in it is either a simple identifier or a Phase A/B property
    // expression / Phase G intrinsic. Literal text (no expansions) is fine.
    // `@(...)` and `%(...)` are NOT allowed.
    static bool AreSimpleExpansionsOnly(string s) {
        for (int i = 0; i < s.Length; i++) {
            var c = s[i];
            if (c == '@' || c == '%') {
                if (i + 1 < s.Length && s[i + 1] == '(') return false;
            }
            if (c == '$' && i + 1 < s.Length && s[i + 1] == '(') {
                var end = FindMatchingParenQuoteAware(s, i + 1);
                if (end < 0) return false;
                var inner = s.Substring(i + 2, end - i - 2);
                if (!IsSimpleExpressionInner(inner)) return false;
                i = end;
            }
        }
        return true;
    }

    // IsSimplePropertyExpression accepts either a bare identifier or a property
    // function chain $(Var.M1(...).M2(...).Prop). Mirrors the runtime's
    // evalPropertyExpression. Methods are whitelisted.
    static bool IsSimplePropertyExpression(string inner) {
        inner = inner.Trim();
        if (inner.Length == 0) return true;
        var dot = IndexOfTopLevel(inner, '.');
        if (dot < 0) return IsSimpleIdentifierName(inner);
        var varName = inner.Substring(0, dot).Trim();
        if (!IsSimpleIdentifierName(varName)) return false;
        var rest = inner.Substring(dot + 1);
        while (rest.Length > 0) {
            int nameEnd = 0;
            while (nameEnd < rest.Length) {
                var c = rest[nameEnd];
                var isIdent = char.IsLetterOrDigit(c) || c == '_';
                if (!isIdent) break;
                nameEnd++;
            }
            if (nameEnd == 0) return false;
            var method = rest.Substring(0, nameEnd);
            rest = rest.Substring(nameEnd);
            bool hasArgs = false;
            string[] args = Array.Empty<string>();
            if (rest.Length > 0 && rest[0] == '(') {
                var close = FindMatchingParenQuoteAware(rest, 0);
                if (close < 0) return false;
                hasArgs = true;
                args = SplitArgsQuoteAware(rest.Substring(1, close - 1));
                rest = rest.Substring(close + 1);
            }
            if (!IsWhitelistedPropertyMethod(method, args.Length, hasArgs)) return false;
            foreach (var arg in args) {
                if (!IsSimplePropertyFunctionArg(arg.Trim())) return false;
            }
            rest = rest.Trim();
            if (rest.Length == 0) break;
            if (rest[0] != '.') return false;
            rest = rest.Substring(1);
        }
        return true;
    }

    static bool IsWhitelistedPropertyMethod(string method, int argCount, bool hasArgs) {
        switch (method.ToLowerInvariant()) {
            case "tolower":
            case "tolowerinvariant":
            case "toupper":
            case "toupperinvariant":
            case "tostring":
            case "length":
                return !hasArgs || argCount == 0;
            case "trim":
            case "trimstart":
            case "trimend":
                return !hasArgs || argCount <= 1;
            case "replace":
                return hasArgs && argCount == 2;
            case "substring":
                return hasArgs && (argCount == 1 || argCount == 2);
            case "startswith":
            case "endswith":
            case "contains":
            case "indexof":
                return hasArgs && argCount == 1;
            default:
                return false;
        }
    }

    static bool IsSimplePropertyFunctionArg(string arg) {
        if (arg.Length == 0) return true;
        if ((arg[0] == '\'' || arg[0] == '"') && arg.Length >= 2 && arg[arg.Length - 1] == arg[0]) {
            // Quoted string literal — inner must not contain expansions (Phase B keeps args atomic).
            return !arg.AsSpan(1, arg.Length - 2).ContainsAny("$@%");
        }
        if (arg.StartsWith("$(", StringComparison.Ordinal) && arg.EndsWith(")", StringComparison.Ordinal)) {
            var inner = arg.Substring(2, arg.Length - 3).Trim();
            return IsSimpleIdentifierName(inner);
        }
        return IsIntegerLiteral(arg);
    }

    static bool IsIntegerLiteral(string s) {
        if (string.IsNullOrEmpty(s)) return false;
        int start = 0;
        if (s[0] == '-' || s[0] == '+') {
            if (s.Length == 1) return false;
            start = 1;
        }
        for (int i = start; i < s.Length; i++) {
            if (s[i] < '0' || s[i] > '9') return false;
        }
        return true;
    }

    static int IndexOfTopLevel(string s, char target) {
        int depth = 0;
        char quote = '\0';
        for (int i = 0; i < s.Length; i++) {
            var c = s[i];
            if (quote != '\0') { if (c == quote) quote = '\0'; continue; }
            switch (c) {
                case '\'': case '"': quote = c; break;
                case '(': depth++; break;
                case ')': if (depth > 0) depth--; break;
                default:
                    if (depth == 0 && c == target) return i;
                    break;
            }
        }
        return -1;
    }

    static string[] SplitArgsQuoteAware(string s) {
        if (string.IsNullOrWhiteSpace(s)) return Array.Empty<string>();
        var parts = new List<string>();
        int depth = 0; char quote = '\0'; int start = 0;
        for (int i = 0; i < s.Length; i++) {
            var c = s[i];
            if (quote != '\0') { if (c == quote) quote = '\0'; continue; }
            switch (c) {
                case '\'': case '"': quote = c; break;
                case '(': depth++; break;
                case ')': depth--; break;
                case ',':
                    if (depth == 0) {
                        parts.Add(s.Substring(start, i - start));
                        start = i + 1;
                    }
                    break;
            }
        }
        parts.Add(s.Substring(start));
        return parts.ToArray();
    }

    static bool IsSimpleConditionTemplate(string? condition) {
        if (string.IsNullOrWhiteSpace(condition)) return true;
        // Reject explicit Phase C+ markers that we don't model. The
        // `[MSBuild]::F(args)` shape is validated via IsSimpleExpressionInner
        // when we walk $() constructs below, so we do NOT blanket-reject
        // `MSBuild::` here.
        if (condition!.IndexOf("System.", StringComparison.Ordinal) >= 0) return false;
        // Reject ANY batching reference anywhere in the condition — `%()` in
        // an operand (even inside quotes) silently expands to "" and matches
        // nothing, which would be wrong-not-loud. Batched conditions need
        // Phase D's batching infrastructure to evaluate correctly.
        if (condition.Contains("%(", StringComparison.Ordinal)) return false;
        // Validate every $() expansion in the condition, including those
        // inside quoted operands. The structural walk below skips quoted
        // sections, so this pass guarantees no quoted intrinsic of an
        // unsupported shape slips through.
        if (!ValidateAllDollarExpansions(condition)) return false;
        // Walk top-level constructs: $(...) must be a simple property expression
        // (Phase A or B form); bare identifiers must be And/Or/Not/True/False or
        // Exists/HasTrailingSlash followed by '('.
        var allowedIdents = new HashSet<string>(StringComparer.OrdinalIgnoreCase) {
            "and", "or", "not", "true", "false", "exists", "hastrailingslash"
        };
        int i = 0;
        char quote = '\0';
        while (i < condition.Length) {
            var c = condition[i];
            if (quote != '\0') {
                if (c == quote) quote = '\0';
                i++;
                continue;
            }
            switch (c) {
                case '<': case '>':
                    // Phase G: numeric / version comparisons (>=, <=, >, <) are
                    // supported by the runtime cond_eval grammar via
                    // NumericCompare. Just skip the operator chars — the
                    // surrounding $() / @() operands are validated separately.
                    if (i + 1 < condition.Length && condition[i + 1] == '=') {
                        i += 2;
                    } else {
                        i++;
                    }
                    continue;
                case '!':
                    // Both `!=` and lone `!<primary>` are supported by the
                    // runtime cond_eval grammar.
                    if (i + 1 < condition.Length && condition[i + 1] == '=') {
                        i += 2;
                    } else {
                        i++;
                    }
                    continue;
                case '\'': case '"': quote = c; i++; continue;
                case '$':
                    if (i + 1 < condition.Length && condition[i + 1] == '(') {
                        var end = FindMatchingParenQuoteAware(condition, i + 1);
                        if (end < 0) return false;
                        var inner = condition.Substring(i + 2, end - i - 2);
                        if (!IsSimpleExpressionInner(inner)) return false;
                        i = end + 1;
                        continue;
                    }
                    i++;
                    continue;
                case '%':
                    return false; // batching in conditions is Phase D+
                case '@':
                    if (i + 1 < condition.Length && condition[i + 1] == '(') {
                        // Allow @(X) and @(X,'sep') in conditions (mirrors expression rules).
                        var end = FindMatchingParenQuoteAware(condition, i + 1);
                        if (end < 0) return false;
                        var inner = condition.Substring(i + 2, end - i - 2);
                        if (inner.Contains("->", StringComparison.Ordinal)) return false;
                        i = end + 1;
                        continue;
                    }
                    i++;
                    continue;
                default:
                    if (char.IsLetter(c) || c == '_') {
                        int wstart = i;
                        while (i < condition.Length && (char.IsLetterOrDigit(condition[i]) || condition[i] == '_')) i++;
                        var word = condition.Substring(wstart, i - wstart);
                        if (!allowedIdents.Contains(word)) return false;
                        // If it's Exists/HasTrailingSlash it must be followed by '('.
                        if (word.Equals("exists", StringComparison.OrdinalIgnoreCase)
                            || word.Equals("hastrailingslash", StringComparison.OrdinalIgnoreCase)) {
                            int j = i;
                            while (j < condition.Length && (condition[j] == ' ' || condition[j] == '\t')) j++;
                            if (j >= condition.Length || condition[j] != '(') return false;
                            var end = FindMatchingParenQuoteAware(condition, j);
                            if (end < 0) return false;
                            // Reject @() / %() inside Exists/HasTrailingSlash args.
                            var argSrc = condition.Substring(j + 1, end - j - 1);
                            if (argSrc.Contains("@(", StringComparison.Ordinal)) return false;
                            if (argSrc.Contains("%(", StringComparison.Ordinal)) return false;
                            i = end + 1;
                        }
                        continue;
                    }
                    i++;
                    continue;
            }
        }
        return quote == '\0';
    }

    // ValidateAllDollarExpansions walks `s` (which may be a condition,
    // expression template, or quoted operand) and returns true iff every
    // `$(...)` / `@(...)` / `%(...)` occurrence — regardless of whether it
    // sits inside quotes or outside — is shape-acceptable to the runtime.
    // Specifically: `$(...)` must satisfy IsSimpleExpressionInner; `@(...)`
    // must not contain `->` (transforms unsupported); `%(...)` is rejected
    // anywhere (batching). This pass complements the structural validators
    // by ensuring quoted operands like `'$([MSBuild]::UnsupportedF(...))' == 'x'`
    // or `'@(X->Count())' != '0'` are caught before reaching the runtime
    // (where they would panic).
    static bool ValidateAllDollarExpansions(string s) {
        for (int i = 0; i < s.Length; i++) {
            var c = s[i];
            if (c == '$' && i + 1 < s.Length && s[i + 1] == '(') {
                var end = FindMatchingParenQuoteAware(s, i + 1);
                if (end < 0) return false;
                var inner = s.Substring(i + 2, end - i - 2);
                if (!IsSimpleExpressionInner(inner)) return false;
                i = end;
                continue;
            }
            if (c == '@' && i + 1 < s.Length && s[i + 1] == '(') {
                var end = FindMatchingParenQuoteAware(s, i + 1);
                if (end < 0) return false;
                var inner = s.Substring(i + 2, end - i - 2);
                if (inner.Contains("->", StringComparison.Ordinal)) return false;
                i = end;
                continue;
            }
            if (c == '%' && i + 1 < s.Length && s[i + 1] == '(') {
                return false;
            }
        }
        return true;
    }

    static int FindMatchingParenQuoteAware(string s, int openIdx) {
        var depth = 0;
        char quote = '\0';
        for (int i = openIdx; i < s.Length; i++) {
            var c = s[i];
            if (quote != '\0') { if (c == quote) quote = '\0'; continue; }
            switch (c) {
                case '\'': case '"': quote = c; break;
                case '(': depth++; break;
                case ')': depth--; if (depth == 0) return i; break;
            }
        }
        return -1;
    }

    static int FindMatchingParen(string s, int openIdx) => FindMatchingParenQuoteAware(s, openIdx);

    static bool ContainsBatching(string? value) {
        if (string.IsNullOrEmpty(value)) return false;
        for (int i = 0; i + 1 < value.Length; i++) {
            if (value[i] == '%' && value[i + 1] == '(') return true;
        }
        return false;
    }

    static bool HasDynamicExtenderAttr(string? attr) {
        if (string.IsNullOrEmpty(attr)) return false;
        return attr!.IndexOfAny(new[] { '$', '@', '%' }) >= 0;
    }

    // BuildExtenderMaps walks targets in declaration order (the order MSBuild
    // inserted them; later definitions of the same name win, which matches
    // MSBuild's "last definition wins" rule) and constructs two maps:
    //   beforeExtenders[X]: list of target names whose BeforeTargets contains X
    //   afterExtenders[X]:  list of target names whose AfterTargets contains X
    // Targets whose Before/AfterTargets are dynamic ($/@/%) are NOT registered;
    // they get rejected by ClassifyTarget as `before-after-dynamic`. Keys are
    // case-insensitive to match dispatchTarget's lowercase lookup.
    static (Dictionary<string, List<string>> Before, Dictionary<string, List<string>> After)
        BuildExtenderMaps(IEnumerable<ProjectTargetInstance> targetsInDeclarationOrder)
    {
        var before = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
        var after = new Dictionary<string, List<string>>(StringComparer.OrdinalIgnoreCase);
        foreach (var t in targetsInDeclarationOrder) {
            if (!string.IsNullOrEmpty(t.BeforeTargets) && !HasDynamicExtenderAttr(t.BeforeTargets)) {
                foreach (var ext in t.BeforeTargets.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)) {
                    if (!before.TryGetValue(ext, out var list)) before[ext] = list = new List<string>();
                    list.Add(t.Name);
                }
            }
            if (!string.IsNullOrEmpty(t.AfterTargets) && !HasDynamicExtenderAttr(t.AfterTargets)) {
                foreach (var ext in t.AfterTargets.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)) {
                    if (!after.TryGetValue(ext, out var list)) after[ext] = list = new List<string>();
                    list.Add(t.Name);
                }
            }
        }
        return (before, after);
    }

    // IsSimpleDependsOnTargetsTemplate validates that a DependsOnTargets template
    // contains only literal text and $(...) property expressions. Returns
    // (true, null) when the template can be safely emitted (literal-only or
    // dynamic-via-runtime-Expand); otherwise (false, reason) where reason is
    // the classifier bucket. Phase C accepts $(SimpleProp) and property
    // function chains $(X.Method().Method2()) — anything the runtime's
    // evalPropertyExpression handles. @() and %() are unsupported here
    // because: item-list refs in a depends-on string are unusual enough to
    // defer (would need explicit semantics), and %() outside a batching
    // context silently expands to empty (wrong-not-loud).
    static (bool ok, string? reason) IsSimpleDependsOnTargetsTemplate(string template) {
        if (string.IsNullOrEmpty(template)) return (true, null);
        if (template.Contains("@(", StringComparison.Ordinal)) return (false, "depends-on-item-ref");
        if (template.Contains("%(", StringComparison.Ordinal)) return (false, "depends-on-batching");
        for (int i = 0; i < template.Length; i++) {
            if (template[i] != '$') continue;
            if (i + 1 >= template.Length || template[i + 1] != '(') {
                // Bare `$` is not a recognized MSBuild form here.
                return (false, "depends-on-complex-expression");
            }
            var end = FindMatchingParenQuoteAware(template, i + 1);
            if (end < 0) return (false, "depends-on-complex-expression");
            var inner = template.Substring(i + 2, end - i - 2);
            // Indexers $(X[...]) and registry $(Registry:...) are not supported.
            if (inner.IndexOfAny(new[] { '[', ':' }) >= 0) return (false, "depends-on-complex-expression");
            if (!IsSimplePropertyExpression(inner)) return (false, "depends-on-complex-expression");
            i = end;
        }
        return (true, null);
    }

    static void EmitMain(StringBuilder sb, ProjectInstance instance, IReadOnlyList<string>? requestedTargets) {
        var defaultEntry = requestedTargets is { Count: > 0 } ? requestedTargets[0] : (instance.DefaultTargets.FirstOrDefault() ?? "Build");
        var projectDir = instance.Directory ?? Path.GetDirectoryName(instance.FullPath) ?? ".";
        sb.AppendLine("func main() {");
        sb.AppendLine("\trt.Log.Level = rt.ParseVerbosity(os.Getenv(\"BSHARP_VERBOSITY\"))");
        sb.AppendLine("\trt.ProjectDir = " + GoStringLiteral(projectDir));
        sb.AppendLine("\tif err := os.Chdir(rt.ProjectDir); err != nil {");
        sb.AppendLine("\t\tfmt.Fprintf(os.Stderr, \"bsharp-go-host: chdir(%q) failed: %v\\n\", rt.ProjectDir, err)");
        sb.AppendLine("\t\tos.Exit(2)");
        sb.AppendLine("\t}");
        sb.AppendLine("\tentry := " + GoStringLiteral(defaultEntry));
        sb.AppendLine("\tif len(os.Args) > 1 { entry = os.Args[1] }");
        sb.AppendLine("\tif !dispatchTarget(entry) {");
        sb.AppendLine("\t\tfmt.Fprintf(os.Stderr, \"bsharp-go-host: unknown target %q\\n\", entry)");
        sb.AppendLine("\t\tos.Exit(2)");
        sb.AppendLine("\t}");
        sb.AppendLine("\tif rt.GetErrorList().HasErrors() {");
        sb.AppendLine("\t\tfmt.Fprint(os.Stderr, rt.GetErrorList().FormatSummary())");
        sb.AppendLine("\t\tos.Exit(1)");
        sb.AppendLine("\t}");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Reference \"strings\" to keep the import alive when no helper uses it.");
        sb.AppendLine("var _ = strings.ToLower");
    }

    static string BuildGoMod(string runtimeReplacePath) {
        var sb = new StringBuilder();
        sb.AppendLine("module bsharp/generated-host");
        sb.AppendLine();
        sb.AppendLine("go 1.21");
        sb.AppendLine();
        sb.AppendLine("require github.com/simonrozsival/bsharp-host-go v0.0.0");
        sb.AppendLine();
        sb.AppendLine("replace github.com/simonrozsival/bsharp-host-go => " + runtimeReplacePath);
        return sb.ToString();
    }

    static string SanitizeTargetName(string name, HashSet<string> existing) {
        var sb = new StringBuilder("Target_");
        foreach (var c in name) {
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        var candidate = sb.ToString();
        var n = 1;
        while (!existing.Add(candidate)) {
            candidate = sb.ToString() + "_" + n++;
        }
        return candidate;
    }

    static string GoStringLiteral(string? value) {
        if (string.IsNullOrEmpty(value)) return "\"\"";
        var sb = new StringBuilder("\"");
        foreach (var c in value) {
            switch (c) {
                case '\\': sb.Append("\\\\"); break;
                case '"':  sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 0x20) sb.AppendFormat("\\u{0:X4}", (int)c);
                    else sb.Append(c);
                    break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    static string EscapeForGo(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    internal sealed class EmitReport {
        public PropertiesReport Properties { get; set; } = new();
        public ItemsReport Items { get; set; } = new();
        public TargetsReport Targets { get; set; } = new();
        public string Note { get; set; } =
            "Phase A scaffold. Real bodies emitted for simple targets; complex ones still panic.";
    }
    internal sealed class PropertiesReport {
        public int Total { get; set; }
        public int SupportedLiteral { get; set; }
    }
    internal sealed class ItemsReport {
        public int TotalTypes { get; set; }
        public int TotalItems { get; set; }
        public int SupportedLiteral { get; set; }
    }
    internal sealed class TargetsReport {
        public int Total { get; set; }
        public int RealBody { get; set; }
        public int StubBody { get; set; }
        public SortedDictionary<string, int> UnsupportedReasons { get; set; } = new(StringComparer.Ordinal);
    }
}
